// GENERATED by scripts/gen-sprites.ts — do not edit.
// Run `npm run gen:sprites` to regenerate. See docs/port/02-sprites.md.

/**
 * One drawable emoji tile. `url` points at a file in public/sprites/.
 *
 * `name` is typed as `string` rather than `SpriteName` to avoid a circular
 * reference — `SpriteName` is derived from `SPRITES`, which is constrained by
 * this interface. Values in `SPRITES` still carry their literal name type.
 */
export interface Sprite {
  readonly name: string
  /** Unicode codepoints, space separated, as they appear in emoji.json. */
  readonly codes: string
  /** The literal emoji character, for text summaries and img alt text. */
  readonly char: string
  readonly url: string
}

export const SPRITES = {
  'elf': { name: 'elf', codes: '1F9DD', char: '🧝', url: '/sprites/1f9dd.svg' },
  'black-large-square': { name: 'black-large-square', codes: '2B1B', char: '⬛', url: '/sprites/2b1b.svg' },
  'white-large-square': { name: 'white-large-square', codes: '2B1C', char: '⬜', url: '/sprites/2b1c.svg' },
  'green-square': { name: 'green-square', codes: '1F7E9', char: '🟩', url: '/sprites/1f7e9.svg' },
  'shinto-shrine': { name: 'shinto-shrine', codes: '26E9', char: '⛩', url: '/sprites/26e9.svg' },
  'chestnut': { name: 'chestnut', codes: '1F330', char: '🌰', url: '/sprites/1f330.svg' },
  'mushroom': { name: 'mushroom', codes: '1F344', char: '🍄', url: '/sprites/1f344.svg' },
  'gem-stone': { name: 'gem-stone', codes: '1F48E', char: '💎', url: '/sprites/1f48e.svg' },
  'tumbler-glass': { name: 'tumbler-glass', codes: '1F943', char: '🥃', url: '/sprites/1f943.svg' },
  'green-heart': { name: 'green-heart', codes: '1F49A', char: '💚', url: '/sprites/1f49a.svg' },
  'shield': { name: 'shield', codes: '1F6E1', char: '🛡', url: '/sprites/1f6e1.svg' },
  'dagger': { name: 'dagger', codes: '1F5E1', char: '🗡', url: '/sprites/1f5e1.svg' },
  'axe': { name: 'axe', codes: '1FA93', char: '🪓', url: '/sprites/1fa93.svg' },
  'potted-plant': { name: 'potted-plant', codes: '1FAB4', char: '🪴', url: '/sprites/1fab4.svg' },
  'rock': { name: 'rock', codes: '1FAA8', char: '🪨', url: '/sprites/1faa8.svg' },
  'wood': { name: 'wood', codes: '1FAB5', char: '🪵', url: '/sprites/1fab5.svg' },
  'rat': { name: 'rat', codes: '1F400', char: '🐀', url: '/sprites/1f400.svg' },
  'bat': { name: 'bat', codes: '1F987', char: '🦇', url: '/sprites/1f987.svg' },
  'ghost': { name: 'ghost', codes: '1F47B', char: '👻', url: '/sprites/1f47b.svg' },
  'boar': { name: 'boar', codes: '1F417', char: '🐗', url: '/sprites/1f417.svg' },
  'wolf': { name: 'wolf', codes: '1F43A', char: '🐺', url: '/sprites/1f43a.svg' },
  'ogre': { name: 'ogre', codes: '1F479', char: '👹', url: '/sprites/1f479.svg' },
  'zombie': { name: 'zombie', codes: '1F9DF', char: '🧟', url: '/sprites/1f9df.svg' },
  'vampire': { name: 'vampire', codes: '1F9DB', char: '🧛', url: '/sprites/1f9db.svg' },
  'genie': { name: 'genie', codes: '1F9DE', char: '🧞', url: '/sprites/1f9de.svg' },
  'dragon': { name: 'dragon', codes: '1F409', char: '🐉', url: '/sprites/1f409.svg' },
  't-rex': { name: 't-rex', codes: '1F996', char: '🦖', url: '/sprites/1f996.svg' },
  'cloud': { name: 'cloud', codes: '2601', char: '☁', url: '/sprites/2601.svg' },
  'collision': { name: 'collision', codes: '1F4A5', char: '💥', url: '/sprites/1f4a5.svg' },
  'skull-and-crossbones': { name: 'skull-and-crossbones', codes: '2620', char: '☠', url: '/sprites/2620.svg' },
  'crossed-swords': { name: 'crossed-swords', codes: '2694', char: '⚔', url: '/sprites/2694.svg' },
  'footprints': { name: 'footprints', codes: '1F463', char: '👣', url: '/sprites/1f463.svg' },
} as const satisfies Record<string, Sprite>

export type SpriteName = keyof typeof SPRITES

/** Typed lookup. Prefer `SPRITES.dragon` where the name is a literal. */
export const sprite = (name: SpriteName): Sprite => SPRITES[name]
