/**
 * Generates the typed sprite index and copies the Twemoji SVGs the game uses.
 *
 * Replaces the compile-time `load-sprite` macro from the original ClojureScript
 * (original/src/rogule/loader.clj). See docs/port/02-sprites.md.
 *
 *   npm run gen:sprites
 *
 * Outputs (both committed, so a fresh clone needs neither source package):
 *   src/game/sprites.ts   typed name -> sprite record
 *   public/sprites/*.svg  the artwork
 *
 * Requires the codegen-only packages:
 *   npm i -D emoji.json twemoji-emojis
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const EMOJI_JSON = join(root, 'node_modules/emoji.json/emoji.json')
const TWEMOJI_SVG_DIR = join(root, 'node_modules/twemoji-emojis/vendor/svg')
const OUT_TS = join(root, 'src/game/sprites.ts')
const OUT_SVG_DIR = join(root, 'public/sprites')

/**
 * Every sprite the game can draw. Seeded from the `load-sprite` calls in the
 * original; the ad and feedback sprites were dropped along with those sections.
 *
 * Names are emoji.json names normalized the same way the original's
 * `name-to-key` did: lowercased, spaces to dashes, other punctuation stripped.
 */
const SPRITE_NAMES = [
  // player and terrain
  'elf',
  'black-large-square', // wall
  'white-large-square', // door, and the empty pip in health/share bars
  'green-square', // the filled pip in health/share bars
  'shinto-shrine', // level exit (becomes stairs in phase 8)

  // forage items
  'chestnut',
  'mushroom',
  'gem-stone',
  'tumbler-glass', // health potion
  'green-heart', // health potion modal
  'shield',
  'dagger',
  'axe',

  // item covers
  'potted-plant',
  'rock',
  'wood',

  // monsters, in difficulty order
  'rat',
  'bat',
  'ghost',
  'boar',
  'wolf',
  'ogre',
  'zombie',
  'vampire',
  'genie',
  'dragon',
  't-rex',

  // effects and summary
  'cloud', // smoke puff when a cover is removed
  'collision', // combat hit marker
  'skull-and-crossbones', // corpses, and death in the summary
  'crossed-swords', // kill list in the summary
  'footprints', // move count in the summary
] as const

type EmojiRecord = { codes: string; char: string; name: string }

/** Mirrors `name-to-key` in original/src/rogule/twemojis.cljc. */
const nameToKey = (name: string): string =>
  name
    .toLowerCase()
    .replace(/ /g, '-')
    .replace(/[^\-\w]+/g, '')

/** Mirrors `codes-to-filename` in original/src/rogule/twemojis.cljc. */
const codesToFilename = (codes: string): string => codes.toLowerCase().replace(/ /g, '-')

function requirePackages(): EmojiRecord[] {
  if (!existsSync(EMOJI_JSON) || !existsSync(TWEMOJI_SVG_DIR)) {
    console.error(
      'Missing codegen dependencies. These are only needed to regenerate sprites\n' +
        '(the generated output is committed), so they are not installed by default:\n\n' +
        '  npm i -D emoji.json twemoji-emojis\n',
    )
    process.exit(1)
  }
  return JSON.parse(readFileSync(EMOJI_JSON, 'utf8')) as EmojiRecord[]
}

function main(): void {
  const emoji = requirePackages()

  // Index by normalized name. The original took the *last* match, so later
  // entries win; preserve that so sprite choices don't shift.
  const byKey = new Map<string, EmojiRecord>()
  for (const e of emoji) byKey.set(nameToKey(e.name), e)

  const available = new Set(readdirSync(TWEMOJI_SVG_DIR))

  rmSync(OUT_SVG_DIR, { recursive: true, force: true })
  mkdirSync(OUT_SVG_DIR, { recursive: true })

  const entries: string[] = []
  const missing: string[] = []

  for (const name of SPRITE_NAMES) {
    const record = byKey.get(name)
    if (!record) {
      missing.push(`${name} (no such emoji name)`)
      continue
    }
    const file = `${codesToFilename(record.codes)}.svg`
    if (!available.has(file)) {
      missing.push(`${name} (no Twemoji artwork at ${file})`)
      continue
    }
    copyFileSync(join(TWEMOJI_SVG_DIR, file), join(OUT_SVG_DIR, file))
    entries.push(
      `  '${name}': { name: '${name}', codes: '${record.codes}', ` +
        `char: '${record.char}', url: '/sprites/${file}' },`,
    )
  }

  if (missing.length > 0) {
    console.error(`Could not resolve ${missing.length} sprite(s):`)
    for (const m of missing) console.error(`  - ${m}`)
    process.exit(1)
  }

  writeFileSync(
    OUT_TS,
    `// GENERATED by scripts/gen-sprites.ts — do not edit.
// Run \`npm run gen:sprites\` to regenerate. See docs/port/02-sprites.md.

/**
 * One drawable emoji tile. \`url\` points at a file in public/sprites/.
 *
 * \`name\` is typed as \`string\` rather than \`SpriteName\` to avoid a circular
 * reference — \`SpriteName\` is derived from \`SPRITES\`, which is constrained by
 * this interface. Values in \`SPRITES\` still carry their literal name type.
 */
export interface Sprite {
  readonly name: string
  /** Unicode codepoints, space separated, as they appear in emoji.json. */
  readonly codes: string
  /** The literal emoji character, for text summaries and img alt text. */
  readonly char: string
  readonly url: string
}

export const SPRITES = {
${entries.join('\n')}
} as const satisfies Record<string, Sprite>

export type SpriteName = keyof typeof SPRITES

/** Typed lookup. Prefer \`SPRITES.dragon\` where the name is a literal. */
export const sprite = (name: SpriteName): Sprite => SPRITES[name]
`,
    'utf8',
  )

  console.log(`Wrote ${entries.length} sprites to src/game/sprites.ts and public/sprites/.`)
}

main()
